### ISSUE TITLE
Require not satisfiable by natxet/cssmin

### ISSUE THREAD

**Issue by emilioastarita** [hellogerard/less-slim-middleware#1]
During the installation of the package with composer I get:

php composer.phar  require hellogerard/less-slim-middleware
Please provide a version constraint for the hellogerard/less-slim-middleware requirement: dev-master
composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for hellogerard/less-slim-middleware dev-master -> satisfiable by hellogerard/less-slim-middleware[dev-master].
    - hellogerard/less-slim-middleware dev-master requires natxet/cssmin dev-master#9801e2a0de7ae252ca4f2b85542d75a82047a8b4 -> no matching package found.

**Comment by hellogerard** [comment]
Looks like it's still not working. I think the author of 'natxet/cssmin' needs to re-submit to Packagist with the new name. Let's wait and see if he does.

**Comment by hellogerard** [comment]
Not sure if something changed, but this appears to be working now.
